services:
  web:
    build: .
    ports:
      - '23000:3000'
    volumes:
      - '.:/verbena'
      - 'bundle:/usr/local/bundle'
    tty: true
    stdin_open: true
    environment:
      VERBENA_DELIVERY_METHOD: smtp
      VERBENA_DELIVERY_SMTP_DOMAIN: localdomain
      VERBENA_DELIVERY_SMTP_AUTHENTICATION: plain
      VERBENA_DELIVERY_SMTP_USER_NAME: dummy
      VERBENA_DELIVERY_SMTP_PASSWORD: dummy
      VERBENA_DELIVERY_SMTP_ADDRESS: mailcatcher
      VERBENA_DELIVERY_SMTP_PORT: 1025

volumes:
  bundle:
