services:
  web:
    build: .
    ports:
      - '23000:3000'
    volumes:
      - '.:/verbena'
      - 'bundle:/usr/local/bundle'
    tty: true
    stdin_open: true
    environment:
      BINDING: 0.0.0.0
      PORT: 3000
      VERBENA_DELIVERY_METHOD: file

volumes:
  bundle:
